---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Denver
  METALLB_LB_RANGE: 10.0.0.102-10.0.0.112
  METALLB_K8S_GATEWAY_ADDR: 10.0.0.102
  METALLB_INGRESS_ADDR: 10.0.0.103
