---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.2.6
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      longhorn:
        engine:
          repository: longhornio/longhorn-engine
          tag: v1.2.3
        manager:
          repository: longhornio/longhorn-manager
          tag: v1.2.3
        ui:
          repository: longhornio/longhorn-ui
          tag: v1.2.3
        instanceManager:
          repository: longhornio/longhorn-instance-manager
          tag: v1_20211210
        shareManager:
          repository: longhornio/longhorn-share-manager
          tag: v1_20211020
        backingImageManager:
          repository: longhornio/backing-image-manager
          tag: v2_20210820
      csi:
        attacher:
          repository: longhornio/csi-attacher
          tag: v3.2.1
        provisioner:
          repository: longhornio/csi-provisioner
          tag: v2.1.2
        nodeDriverRegistrar:
          repository: longhornio/csi-node-driver-registrar
          tag: v2.3.0
        resizer:
          repository: longhornio/csi-resizer
          tag: v1.2.0
        snapshotter:
          repository: longhornio/csi-snapshotter
          tag: v3.0.3
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/enable: "true"
        hajimari.io/icon: "weather-sunset"
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true
      tlsSecret: "longhorn-tls"
